[package]
name = "send-vrc-desktop"
version = "1.0.5"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.61"
axum = "0.5.15"
time = { version = "0.3.13", features = ["local-offset"] }
tokio = { version = "1.20.1", features = ["full"] }
serde = { version = "1.0.143", features = ["derive"] }
clipboard-win = "4.4.2"
windows = { version = "0.39.0", features = ["Win32_Foundation", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_WindowsAndMessaging"] }
