[package]
name = "send_vrc_desktop"
version = "1.0.5"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.69"
axum = "0.6.6"
time = { version = "0.3.17", features = ["local-offset"] }
tokio = { version = "1.25.0", features = ["full"] }
serde = { version = "1.0.152", features = ["derive"] }
clipboard-win = "4.5.0"
windows = { version = "0.44.0", features = ["Win32_Foundation", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_WindowsAndMessaging"] }
