[package]
name = "send_vrc_desktop"
version = "1.0.6"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.75"
axum = "0.6.20"
time = { version = "0.3.25", features = ["local-offset"] }
tokio = { version = "1.31.0", features = ["full"] }
serde = { version = "1.0.183", features = ["derive"] }
clipboard-win = "4.5.0"
windows = { version = "0.48.0", features = ["Win32_Foundation", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_WindowsAndMessaging"] }
